# Generated by Django 2.1.7 on 2019-03-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursedboundapp', '0002_auto_20190307_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
